// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `ObjectDetection.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <ObjectDetection.h>
#include <Ice/LocalException.h>
#include <Ice/ObjectFactory.h>
#include <Ice/BasicStream.h>
#include <Ice/Object.h>
#include <IceUtil/Iterator.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 305
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 1
#       error Ice patch level mismatch!
#   endif
#endif

namespace
{

const ::std::string __RoboCompObjectDetection__ObjectDetection__findObjects_name = "findObjects";

}

namespace Ice
{
}
::IceProxy::Ice::Object* ::IceProxy::RoboCompObjectDetection::upCast(::IceProxy::RoboCompObjectDetection::ObjectDetection* p) { return p; }

void
::IceProxy::RoboCompObjectDetection::__read(::IceInternal::BasicStream* __is, ::IceInternal::ProxyHandle< ::IceProxy::RoboCompObjectDetection::ObjectDetection>& v)
{
    ::Ice::ObjectPrx proxy;
    __is->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::RoboCompObjectDetection::ObjectDetection;
        v->__copyFrom(proxy);
    }
}

bool
IceProxy::RoboCompObjectDetection::ObjectDetection::findObjects(const ::RoboCompObjectDetection::StringVector& objectsTofind, ::RoboCompObjectDetection::ObjectVector& objects, const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __RoboCompObjectDetection__ObjectDetection__findObjects_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __checkTwowayOnly(__RoboCompObjectDetection__ObjectDetection__findObjects_name);
            __delBase = __getDelegate(false);
            ::IceDelegate::RoboCompObjectDetection::ObjectDetection* __del = dynamic_cast< ::IceDelegate::RoboCompObjectDetection::ObjectDetection*>(__delBase.get());
            return __del->findObjects(objectsTofind, objects, __ctx, __observer);
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::RoboCompObjectDetection::ObjectDetection::begin_findObjects(const ::RoboCompObjectDetection::StringVector& objectsTofind, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__RoboCompObjectDetection__ObjectDetection__findObjects_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __RoboCompObjectDetection__ObjectDetection__findObjects_name, __del, __cookie);
    try
    {
        __result->__prepare(__RoboCompObjectDetection__ObjectDetection__findObjects_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__startWriteParams(::Ice::DefaultFormat);
        __os->write(objectsTofind);
        __result->__endWriteParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

bool
IceProxy::RoboCompObjectDetection::ObjectDetection::end_findObjects(::RoboCompObjectDetection::ObjectVector& objects, const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __RoboCompObjectDetection__ObjectDetection__findObjects_name);
    bool __ret;
    bool __ok = __result->__wait();
    try
    {
        if(!__ok)
        {
            try
            {
                __result->__throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
            }
        }
        ::IceInternal::BasicStream* __is = __result->__startReadParams();
        __is->read(objects);
        __is->read(__ret);
        __result->__endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& ex)
    {
        __result->__getObserver().failed(ex.ice_name());
        throw;
    }
}

const ::std::string&
IceProxy::RoboCompObjectDetection::ObjectDetection::ice_staticId()
{
    return ::RoboCompObjectDetection::ObjectDetection::ice_staticId();
}

::IceInternal::Handle< ::IceDelegateM::Ice::Object>
IceProxy::RoboCompObjectDetection::ObjectDetection::__createDelegateM()
{
    return ::IceInternal::Handle< ::IceDelegateM::Ice::Object>(new ::IceDelegateM::RoboCompObjectDetection::ObjectDetection);
}

::IceInternal::Handle< ::IceDelegateD::Ice::Object>
IceProxy::RoboCompObjectDetection::ObjectDetection::__createDelegateD()
{
    return ::IceInternal::Handle< ::IceDelegateD::Ice::Object>(new ::IceDelegateD::RoboCompObjectDetection::ObjectDetection);
}

::IceProxy::Ice::Object*
IceProxy::RoboCompObjectDetection::ObjectDetection::__newInstance() const
{
    return new ObjectDetection;
}

bool
IceDelegateM::RoboCompObjectDetection::ObjectDetection::findObjects(const ::RoboCompObjectDetection::StringVector& objectsTofind, ::RoboCompObjectDetection::ObjectVector& objects, const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __RoboCompObjectDetection__ObjectDetection__findObjects_name, ::Ice::Normal, __context, __observer);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(objectsTofind);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    bool __ret;
    try
    {
        if(!__ok)
        {
            try
            {
                __og.throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                throw __uue;
            }
        }
        ::IceInternal::BasicStream* __is = __og.startReadParams();
        __is->read(objects);
        __is->read(__ret);
        __og.endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& __ex)
    {
        throw ::IceInternal::LocalExceptionWrapper(__ex, false);
    }
}

bool
IceDelegateD::RoboCompObjectDetection::ObjectDetection::findObjects(const ::RoboCompObjectDetection::StringVector& objectsTofind, ::RoboCompObjectDetection::ObjectVector& objects, const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(bool& __result, const ::RoboCompObjectDetection::StringVector& __p_objectsTofind, ::RoboCompObjectDetection::ObjectVector& __p_objects, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _result(__result),
            _m_objectsTofind(__p_objectsTofind),
            _m_objects(__p_objects)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::RoboCompObjectDetection::ObjectDetection* servant = dynamic_cast< ::RoboCompObjectDetection::ObjectDetection*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            _result = servant->findObjects(_m_objectsTofind, _m_objects, _current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        bool& _result;
        const ::RoboCompObjectDetection::StringVector& _m_objectsTofind;
        ::RoboCompObjectDetection::ObjectVector& _m_objects;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __RoboCompObjectDetection__ObjectDetection__findObjects_name, ::Ice::Normal, __context);
    bool __result;
    try
    {
        _DirectI __direct(__result, objectsTofind, objects, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
    return __result;
}

::Ice::Object* RoboCompObjectDetection::upCast(::RoboCompObjectDetection::ObjectDetection* p) { return p; }

namespace
{
const ::std::string __RoboCompObjectDetection__ObjectDetection_ids[2] =
{
    "::Ice::Object",
    "::RoboCompObjectDetection::ObjectDetection"
};

}

bool
RoboCompObjectDetection::ObjectDetection::ice_isA(const ::std::string& _s, const ::Ice::Current&) const
{
    return ::std::binary_search(__RoboCompObjectDetection__ObjectDetection_ids, __RoboCompObjectDetection__ObjectDetection_ids + 2, _s);
}

::std::vector< ::std::string>
RoboCompObjectDetection::ObjectDetection::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&__RoboCompObjectDetection__ObjectDetection_ids[0], &__RoboCompObjectDetection__ObjectDetection_ids[2]);
}

const ::std::string&
RoboCompObjectDetection::ObjectDetection::ice_id(const ::Ice::Current&) const
{
    return __RoboCompObjectDetection__ObjectDetection_ids[1];
}

const ::std::string&
RoboCompObjectDetection::ObjectDetection::ice_staticId()
{
    return __RoboCompObjectDetection__ObjectDetection_ids[1];
}

::Ice::DispatchStatus
RoboCompObjectDetection::ObjectDetection::___findObjects(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::RoboCompObjectDetection::StringVector objectsTofind;
    __is->read(objectsTofind);
    __inS.endReadParams();
    ::RoboCompObjectDetection::ObjectVector objects;
    bool __ret = findObjects(objectsTofind, objects, __current);
    ::IceInternal::BasicStream* __os = __inS.__startWriteParams(::Ice::DefaultFormat);
    __os->write(objects);
    __os->write(__ret);
    __inS.__endWriteParams(true);
    return ::Ice::DispatchOK;
}

namespace
{
const ::std::string __RoboCompObjectDetection__ObjectDetection_all[] =
{
    "findObjects",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping"
};

}

::Ice::DispatchStatus
RoboCompObjectDetection::ObjectDetection::__dispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair< const ::std::string*, const ::std::string*> r = ::std::equal_range(__RoboCompObjectDetection__ObjectDetection_all, __RoboCompObjectDetection__ObjectDetection_all + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - __RoboCompObjectDetection__ObjectDetection_all)
    {
        case 0:
        {
            return ___findObjects(in, current);
        }
        case 1:
        {
            return ___ice_id(in, current);
        }
        case 2:
        {
            return ___ice_ids(in, current);
        }
        case 3:
        {
            return ___ice_isA(in, current);
        }
        case 4:
        {
            return ___ice_ping(in, current);
        }
    }

    assert(false);
    throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
}

void
RoboCompObjectDetection::ObjectDetection::__writeImpl(::IceInternal::BasicStream* __os) const
{
    __os->startWriteSlice(ice_staticId(), -1, true);
    __os->endWriteSlice();
}

void
RoboCompObjectDetection::ObjectDetection::__readImpl(::IceInternal::BasicStream* __is)
{
    __is->startReadSlice();
    __is->endReadSlice();
}

void 
RoboCompObjectDetection::__patch(ObjectDetectionPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ::RoboCompObjectDetection::ObjectDetectionPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(::RoboCompObjectDetection::ObjectDetection::ice_staticId(), v);
    }
}
