// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `ObjectDetection.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef ____ObjectDetection_h__
#define ____ObjectDetection_h__

#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/StreamHelpers.h>
#include <Ice/Proxy.h>
#include <Ice/Object.h>
#include <Ice/Outgoing.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/Incoming.h>
#include <Ice/Direct.h>
#include <IceUtil/ScopedArray.h>
#include <IceUtil/Optional.h>
#include <Ice/StreamF.h>
#include <Ice/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 305
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 1
#       error Ice patch level mismatch!
#   endif
#endif

namespace IceProxy
{

namespace RoboCompObjectDetection
{

class ObjectDetection;
void __read(::IceInternal::BasicStream*, ::IceInternal::ProxyHandle< ::IceProxy::RoboCompObjectDetection::ObjectDetection>&);
::IceProxy::Ice::Object* upCast(::IceProxy::RoboCompObjectDetection::ObjectDetection*);

}

}

namespace RoboCompObjectDetection
{

class ObjectDetection;
bool operator==(const ObjectDetection&, const ObjectDetection&);
bool operator<(const ObjectDetection&, const ObjectDetection&);
::Ice::Object* upCast(::RoboCompObjectDetection::ObjectDetection*);
typedef ::IceInternal::Handle< ::RoboCompObjectDetection::ObjectDetection> ObjectDetectionPtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::RoboCompObjectDetection::ObjectDetection> ObjectDetectionPrx;
void __patch(ObjectDetectionPtr&, const ::Ice::ObjectPtr&);

}

namespace RoboCompObjectDetection
{

typedef ::std::vector< ::std::string> StringVector;

struct ObjectType
{
    ::std::string label;
    ::Ice::Float tx;
    ::Ice::Float ty;
    ::Ice::Float tz;
    ::Ice::Float rx;
    ::Ice::Float ry;
    ::Ice::Float rz;
    ::Ice::Float minx;
    ::Ice::Float miny;
    ::Ice::Float minz;
    ::Ice::Float maxx;
    ::Ice::Float maxy;
    ::Ice::Float maxz;
};

typedef ::std::vector< ::RoboCompObjectDetection::ObjectType> ObjectVector;

}

namespace Ice
{
template<>
struct StreamableTraits< ::RoboCompObjectDetection::ObjectType>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 49;
    static const bool fixedLength = false;
};

template<class S>
struct StreamWriter< ::RoboCompObjectDetection::ObjectType, S>
{
    static void write(S* __os, const ::RoboCompObjectDetection::ObjectType& v)
    {
        __os->write(v.label);
        __os->write(v.tx);
        __os->write(v.ty);
        __os->write(v.tz);
        __os->write(v.rx);
        __os->write(v.ry);
        __os->write(v.rz);
        __os->write(v.minx);
        __os->write(v.miny);
        __os->write(v.minz);
        __os->write(v.maxx);
        __os->write(v.maxy);
        __os->write(v.maxz);
    }
};

template<class S>
struct StreamReader< ::RoboCompObjectDetection::ObjectType, S>
{
    static void read(S* __is, ::RoboCompObjectDetection::ObjectType& v)
    {
        __is->read(v.label);
        __is->read(v.tx);
        __is->read(v.ty);
        __is->read(v.tz);
        __is->read(v.rx);
        __is->read(v.ry);
        __is->read(v.rz);
        __is->read(v.minx);
        __is->read(v.miny);
        __is->read(v.minz);
        __is->read(v.maxx);
        __is->read(v.maxy);
        __is->read(v.maxz);
    }
};

}

namespace RoboCompObjectDetection
{

class Callback_ObjectDetection_findObjects_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_ObjectDetection_findObjects_Base> Callback_ObjectDetection_findObjectsPtr;

}

namespace IceProxy
{

namespace RoboCompObjectDetection
{

class ObjectDetection : virtual public ::IceProxy::Ice::Object
{
public:

    bool findObjects(const ::RoboCompObjectDetection::StringVector& objectsTofind, ::RoboCompObjectDetection::ObjectVector& objects)
    {
        return findObjects(objectsTofind, objects, 0);
    }
    bool findObjects(const ::RoboCompObjectDetection::StringVector& objectsTofind, ::RoboCompObjectDetection::ObjectVector& objects, const ::Ice::Context& __ctx)
    {
        return findObjects(objectsTofind, objects, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_findObjects(const ::RoboCompObjectDetection::StringVector& objectsTofind, const ::IceInternal::Function<void (bool, const ::RoboCompObjectDetection::ObjectVector&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_findObjects(objectsTofind, 0, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_findObjects(const ::RoboCompObjectDetection::StringVector& objectsTofind, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_findObjects(objectsTofind, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_findObjects(const ::RoboCompObjectDetection::StringVector& objectsTofind, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (bool, const ::RoboCompObjectDetection::ObjectVector&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_findObjects(objectsTofind, &__ctx, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_findObjects(const ::RoboCompObjectDetection::StringVector& objectsTofind, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_findObjects(objectsTofind, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
    
private:

    ::Ice::AsyncResultPtr __begin_findObjects(const ::RoboCompObjectDetection::StringVector& objectsTofind, const ::Ice::Context* __ctx, const ::IceInternal::Function<void (bool, const ::RoboCompObjectDetection::ObjectVector&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent)
    {
        class Cpp11CB : public ::IceInternal::Cpp11FnCallbackNC
        {
        public:

            Cpp11CB(const ::std::function<void (bool, const ::RoboCompObjectDetection::ObjectVector&)>& responseFunc, const ::std::function<void (const ::Ice::Exception&)>& exceptionFunc, const ::std::function<void (bool)>& sentFunc) :
                ::IceInternal::Cpp11FnCallbackNC(exceptionFunc, sentFunc),
                _response(responseFunc)
            {
                CallbackBase::checkCallback(true, responseFunc || exceptionFunc != nullptr);
            }

            virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
            {
                ::RoboCompObjectDetection::ObjectDetectionPrx __proxy = ::RoboCompObjectDetection::ObjectDetectionPrx::uncheckedCast(__result->getProxy());
                ::RoboCompObjectDetection::ObjectVector objects;
                bool __ret;
                try
                {
                    __ret = __proxy->end_findObjects(objects, __result);
                }
                catch(::Ice::Exception& ex)
                {
                    Cpp11FnCallbackNC::__exception(__result, ex);
                    return;
                }
                if(_response != nullptr)
                {
                    _response(__ret, objects);
                }
            }
        
        private:
            
            ::std::function<void (bool, const ::RoboCompObjectDetection::ObjectVector&)> _response;
        };
        return begin_findObjects(objectsTofind, __ctx, new Cpp11CB(__response, __exception, __sent));
    }
    
public:
#endif

    ::Ice::AsyncResultPtr begin_findObjects(const ::RoboCompObjectDetection::StringVector& objectsTofind)
    {
        return begin_findObjects(objectsTofind, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_findObjects(const ::RoboCompObjectDetection::StringVector& objectsTofind, const ::Ice::Context& __ctx)
    {
        return begin_findObjects(objectsTofind, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_findObjects(const ::RoboCompObjectDetection::StringVector& objectsTofind, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_findObjects(objectsTofind, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_findObjects(const ::RoboCompObjectDetection::StringVector& objectsTofind, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_findObjects(objectsTofind, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_findObjects(const ::RoboCompObjectDetection::StringVector& objectsTofind, const ::RoboCompObjectDetection::Callback_ObjectDetection_findObjectsPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_findObjects(objectsTofind, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_findObjects(const ::RoboCompObjectDetection::StringVector& objectsTofind, const ::Ice::Context& __ctx, const ::RoboCompObjectDetection::Callback_ObjectDetection_findObjectsPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_findObjects(objectsTofind, &__ctx, __del, __cookie);
    }

    bool end_findObjects(::RoboCompObjectDetection::ObjectVector& objects, const ::Ice::AsyncResultPtr&);
    
private:

    bool findObjects(const ::RoboCompObjectDetection::StringVector&, ::RoboCompObjectDetection::ObjectVector&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_findObjects(const ::RoboCompObjectDetection::StringVector&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:
    
    ::IceInternal::ProxyHandle<ObjectDetection> ice_context(const ::Ice::Context& __context) const
    {
        return dynamic_cast<ObjectDetection*>(::IceProxy::Ice::Object::ice_context(__context).get());
    }
    
    ::IceInternal::ProxyHandle<ObjectDetection> ice_adapterId(const ::std::string& __id) const
    {
        return dynamic_cast<ObjectDetection*>(::IceProxy::Ice::Object::ice_adapterId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<ObjectDetection> ice_endpoints(const ::Ice::EndpointSeq& __endpoints) const
    {
        return dynamic_cast<ObjectDetection*>(::IceProxy::Ice::Object::ice_endpoints(__endpoints).get());
    }
    
    ::IceInternal::ProxyHandle<ObjectDetection> ice_locatorCacheTimeout(int __timeout) const
    {
        return dynamic_cast<ObjectDetection*>(::IceProxy::Ice::Object::ice_locatorCacheTimeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<ObjectDetection> ice_connectionCached(bool __cached) const
    {
        return dynamic_cast<ObjectDetection*>(::IceProxy::Ice::Object::ice_connectionCached(__cached).get());
    }
    
    ::IceInternal::ProxyHandle<ObjectDetection> ice_endpointSelection(::Ice::EndpointSelectionType __est) const
    {
        return dynamic_cast<ObjectDetection*>(::IceProxy::Ice::Object::ice_endpointSelection(__est).get());
    }
    
    ::IceInternal::ProxyHandle<ObjectDetection> ice_secure(bool __secure) const
    {
        return dynamic_cast<ObjectDetection*>(::IceProxy::Ice::Object::ice_secure(__secure).get());
    }
    
    ::IceInternal::ProxyHandle<ObjectDetection> ice_preferSecure(bool __preferSecure) const
    {
        return dynamic_cast<ObjectDetection*>(::IceProxy::Ice::Object::ice_preferSecure(__preferSecure).get());
    }
    
    ::IceInternal::ProxyHandle<ObjectDetection> ice_router(const ::Ice::RouterPrx& __router) const
    {
        return dynamic_cast<ObjectDetection*>(::IceProxy::Ice::Object::ice_router(__router).get());
    }
    
    ::IceInternal::ProxyHandle<ObjectDetection> ice_locator(const ::Ice::LocatorPrx& __locator) const
    {
        return dynamic_cast<ObjectDetection*>(::IceProxy::Ice::Object::ice_locator(__locator).get());
    }
    
    ::IceInternal::ProxyHandle<ObjectDetection> ice_collocationOptimized(bool __co) const
    {
        return dynamic_cast<ObjectDetection*>(::IceProxy::Ice::Object::ice_collocationOptimized(__co).get());
    }
    
    ::IceInternal::ProxyHandle<ObjectDetection> ice_twoway() const
    {
        return dynamic_cast<ObjectDetection*>(::IceProxy::Ice::Object::ice_twoway().get());
    }
    
    ::IceInternal::ProxyHandle<ObjectDetection> ice_oneway() const
    {
        return dynamic_cast<ObjectDetection*>(::IceProxy::Ice::Object::ice_oneway().get());
    }
    
    ::IceInternal::ProxyHandle<ObjectDetection> ice_batchOneway() const
    {
        return dynamic_cast<ObjectDetection*>(::IceProxy::Ice::Object::ice_batchOneway().get());
    }
    
    ::IceInternal::ProxyHandle<ObjectDetection> ice_datagram() const
    {
        return dynamic_cast<ObjectDetection*>(::IceProxy::Ice::Object::ice_datagram().get());
    }
    
    ::IceInternal::ProxyHandle<ObjectDetection> ice_batchDatagram() const
    {
        return dynamic_cast<ObjectDetection*>(::IceProxy::Ice::Object::ice_batchDatagram().get());
    }
    
    ::IceInternal::ProxyHandle<ObjectDetection> ice_compress(bool __compress) const
    {
        return dynamic_cast<ObjectDetection*>(::IceProxy::Ice::Object::ice_compress(__compress).get());
    }
    
    ::IceInternal::ProxyHandle<ObjectDetection> ice_timeout(int __timeout) const
    {
        return dynamic_cast<ObjectDetection*>(::IceProxy::Ice::Object::ice_timeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<ObjectDetection> ice_connectionId(const ::std::string& __id) const
    {
        return dynamic_cast<ObjectDetection*>(::IceProxy::Ice::Object::ice_connectionId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<ObjectDetection> ice_encodingVersion(const ::Ice::EncodingVersion& __v) const
    {
        return dynamic_cast<ObjectDetection*>(::IceProxy::Ice::Object::ice_encodingVersion(__v).get());
    }
    
    static const ::std::string& ice_staticId();

private: 

    virtual ::IceInternal::Handle< ::IceDelegateM::Ice::Object> __createDelegateM();
    virtual ::IceInternal::Handle< ::IceDelegateD::Ice::Object> __createDelegateD();
    virtual ::IceProxy::Ice::Object* __newInstance() const;
};

}

}

namespace IceDelegate
{

namespace RoboCompObjectDetection
{

class ObjectDetection : virtual public ::IceDelegate::Ice::Object
{
public:

    virtual bool findObjects(const ::RoboCompObjectDetection::StringVector&, ::RoboCompObjectDetection::ObjectVector&, const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;
};

}

}

namespace IceDelegateM
{

namespace RoboCompObjectDetection
{

class ObjectDetection : virtual public ::IceDelegate::RoboCompObjectDetection::ObjectDetection,
                        virtual public ::IceDelegateM::Ice::Object
{
public:

    virtual bool findObjects(const ::RoboCompObjectDetection::StringVector&, ::RoboCompObjectDetection::ObjectVector&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);
};

}

}

namespace IceDelegateD
{

namespace RoboCompObjectDetection
{

class ObjectDetection : virtual public ::IceDelegate::RoboCompObjectDetection::ObjectDetection,
                        virtual public ::IceDelegateD::Ice::Object
{
public:

    virtual bool findObjects(const ::RoboCompObjectDetection::StringVector&, ::RoboCompObjectDetection::ObjectVector&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);
};

}

}

namespace RoboCompObjectDetection
{

class ObjectDetection : virtual public ::Ice::Object
{
public:

    typedef ObjectDetectionPrx ProxyType;
    typedef ObjectDetectionPtr PointerType;

    virtual bool ice_isA(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) const;
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& = ::Ice::Current()) const;
    virtual const ::std::string& ice_id(const ::Ice::Current& = ::Ice::Current()) const;
    static const ::std::string& ice_staticId();

    virtual bool findObjects(const ::RoboCompObjectDetection::StringVector&, ::RoboCompObjectDetection::ObjectVector&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___findObjects(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Ice::DispatchStatus __dispatch(::IceInternal::Incoming&, const ::Ice::Current&);

protected:
    virtual void __writeImpl(::IceInternal::BasicStream*) const;
    virtual void __readImpl(::IceInternal::BasicStream*);
    #ifdef __SUNPRO_CC
    using ::Ice::Object::__writeImpl;
    using ::Ice::Object::__readImpl;
    #endif
};

inline bool operator==(const ObjectDetection& l, const ObjectDetection& r)
{
    return static_cast<const ::Ice::Object&>(l) == static_cast<const ::Ice::Object&>(r);
}

inline bool operator<(const ObjectDetection& l, const ObjectDetection& r)
{
    return static_cast<const ::Ice::Object&>(l) < static_cast<const ::Ice::Object&>(r);
}

}

namespace RoboCompObjectDetection
{

template<class T>
class CallbackNC_ObjectDetection_findObjects : public Callback_ObjectDetection_findObjects_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(bool, const ::RoboCompObjectDetection::ObjectVector&);

    CallbackNC_ObjectDetection_findObjects(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::RoboCompObjectDetection::ObjectDetectionPrx __proxy = ::RoboCompObjectDetection::ObjectDetectionPrx::uncheckedCast(__result->getProxy());
        ::RoboCompObjectDetection::ObjectVector objects;
        bool __ret;
        try
        {
            __ret = __proxy->end_findObjects(objects, __result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::CallbackNC<T>::callback.get()->*response)(__ret, objects);
        }
    }

    Response response;
};

template<class T> Callback_ObjectDetection_findObjectsPtr
newCallback_ObjectDetection_findObjects(const IceUtil::Handle<T>& instance, void (T::*cb)(bool, const ::RoboCompObjectDetection::ObjectVector&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_ObjectDetection_findObjects<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_ObjectDetection_findObjectsPtr
newCallback_ObjectDetection_findObjects(T* instance, void (T::*cb)(bool, const ::RoboCompObjectDetection::ObjectVector&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_ObjectDetection_findObjects<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_ObjectDetection_findObjects : public Callback_ObjectDetection_findObjects_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(bool, const ::RoboCompObjectDetection::ObjectVector&, const CT&);

    Callback_ObjectDetection_findObjects(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::RoboCompObjectDetection::ObjectDetectionPrx __proxy = ::RoboCompObjectDetection::ObjectDetectionPrx::uncheckedCast(__result->getProxy());
        ::RoboCompObjectDetection::ObjectVector objects;
        bool __ret;
        try
        {
            __ret = __proxy->end_findObjects(objects, __result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::Callback<T, CT>::callback.get()->*response)(__ret, objects, CT::dynamicCast(__result->getCookie()));
        }
    }

    Response response;
};

template<class T, typename CT> Callback_ObjectDetection_findObjectsPtr
newCallback_ObjectDetection_findObjects(const IceUtil::Handle<T>& instance, void (T::*cb)(bool, const ::RoboCompObjectDetection::ObjectVector&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_ObjectDetection_findObjects<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_ObjectDetection_findObjectsPtr
newCallback_ObjectDetection_findObjects(T* instance, void (T::*cb)(bool, const ::RoboCompObjectDetection::ObjectVector&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_ObjectDetection_findObjects<T, CT>(instance, cb, excb, sentcb);
}

}

#endif
